[MFLOG|0|2023-12-15T15:47:19.276584Z|runtime|e62b5bc4-8442-42c9-a2a6-44c191671954]<flow SearchTermDataValidationFlow step end> failed:
[MFLOG|0|2023-12-15T15:47:19.284606Z|runtime|0c0726dc-2ad0-4e48-9b2f-5877af21341f]    Internal error
[MFLOG|0|2023-12-15T15:47:19.287301Z|runtime|69ed575f-01b0-49db-9628-89850d2d2ad5]Traceback (most recent call last):
[MFLOG|0|2023-12-15T15:47:19.287381Z|runtime|aa02b942-7a0b-4672-8b67-3e0d0bdb63eb]  File "/Users/chelseatroy/mozilla/docker-etl/jobs/search-term-data-validation-v2/stdvv2-venv/lib/python3.11/site-packages/metaflow/cli.py", line 1175, in main
[MFLOG|0|2023-12-15T15:47:19.287467Z|runtime|d93964dd-43bc-4b64-882f-a546056e2c2f]    start(auto_envvar_prefix="METAFLOW", obj=state)
[MFLOG|0|2023-12-15T15:47:19.287493Z|runtime|586ec66f-f401-4316-862e-15c78b6f6fdb]  File "/Users/chelseatroy/mozilla/docker-etl/jobs/search-term-data-validation-v2/stdvv2-venv/lib/python3.11/site-packages/metaflow/tracing/__init__.py", line 27, in wrapper_func
[MFLOG|0|2023-12-15T15:47:19.287539Z|runtime|6a35f8f4-4fa6-4476-97da-2d07624e10bb]    return func(args, kwargs)
[MFLOG|0|2023-12-15T15:47:19.624409Z|runtime|e1b6db6c-3eaf-4cff-8be2-661a6dd7e7bc]           ^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2023-12-15T15:47:19.624544Z|runtime|fc36f471-9c39-4e43-87d6-3ca56380e2da]  File "/Users/chelseatroy/mozilla/docker-etl/jobs/search-term-data-validation-v2/stdvv2-venv/lib/python3.11/site-packages/metaflow/_vendor/click/core.py", line 829, in __call__
[MFLOG|0|2023-12-15T15:47:19.624589Z|runtime|6ffde34b-5842-4100-99a6-c06dec8af2ab]    return self.main(args, kwargs)
[MFLOG|0|2023-12-15T15:47:19.624624Z|runtime|0a6b6b57-3ea7-4446-9963-b975103315ea]           ^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2023-12-15T15:47:19.624647Z|runtime|326e13df-8ce4-4213-b46e-d83ad2557200]  File "/Users/chelseatroy/mozilla/docker-etl/jobs/search-term-data-validation-v2/stdvv2-venv/lib/python3.11/site-packages/metaflow/_vendor/click/core.py", line 782, in main
[MFLOG|0|2023-12-15T15:47:19.624675Z|runtime|ac7f653f-16dc-4a09-84a5-6083393b7d66]    rv = self.invoke(ctx)
[MFLOG|0|2023-12-15T15:47:19.624692Z|runtime|1acc3738-bf6d-41e9-b7dd-cb897388333d]         ^^^^^^^^^^^^^^^^
[MFLOG|0|2023-12-15T15:47:19.624721Z|runtime|82a06315-668a-49ff-9da8-54e0de7eccd5]  File "/Users/chelseatroy/mozilla/docker-etl/jobs/search-term-data-validation-v2/stdvv2-venv/lib/python3.11/site-packages/metaflow/_vendor/click/core.py", line 1259, in invoke
[MFLOG|0|2023-12-15T15:47:19.624739Z|runtime|e4a99b84-59ea-4bd0-b2b4-caea8146bc7b]    return _process_result(sub_ctx.command.invoke(sub_ctx))
[MFLOG|0|2023-12-15T15:47:19.624756Z|runtime|ecfee5c1-e89b-4f1a-99b4-40894f31ab8c]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2023-12-15T15:47:19.624775Z|runtime|28ce7c3c-fc94-4a25-9283-296f841b4bd1]  File "/Users/chelseatroy/mozilla/docker-etl/jobs/search-term-data-validation-v2/stdvv2-venv/lib/python3.11/site-packages/metaflow/_vendor/click/core.py", line 1066, in invoke
[MFLOG|0|2023-12-15T15:47:19.624794Z|runtime|d3270502-01f1-43e7-94c2-d385bea24dee]    return ctx.invoke(self.callback, ctx.params)
[MFLOG|0|2023-12-15T15:47:19.624815Z|runtime|598a2710-fe68-4e1b-a0c5-02609d8b70ab]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2023-12-15T15:47:19.624837Z|runtime|0bfed00a-fe11-4e57-ad80-4e996da6326f]  File "/Users/chelseatroy/mozilla/docker-etl/jobs/search-term-data-validation-v2/stdvv2-venv/lib/python3.11/site-packages/metaflow/_vendor/click/core.py", line 610, in invoke
[MFLOG|0|2023-12-15T15:47:19.624891Z|runtime|c51c7844-d63d-4bee-bd80-c910ce85d28a]    return callback(args, kwargs)
[MFLOG|0|2023-12-15T15:47:19.624910Z|runtime|c151b8d6-20cf-44e4-8d92-9438866ada8f]           ^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2023-12-15T15:47:19.624928Z|runtime|8f75fc77-6f68-41b2-8139-fde0e482db36]  File "/Users/chelseatroy/mozilla/docker-etl/jobs/search-term-data-validation-v2/stdvv2-venv/lib/python3.11/site-packages/metaflow/_vendor/click/decorators.py", line 21, in new_func
[MFLOG|0|2023-12-15T15:47:19.624945Z|runtime|0914fc25-2d2c-4380-b7ea-febf2c07a765]    return f(get_current_context(), args, kwargs)
[MFLOG|0|2023-12-15T15:47:19.624963Z|runtime|083636d2-1a6a-4a2c-bc85-190750ae1395]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2023-12-15T15:47:19.624981Z|runtime|3a83c65d-05aa-44ec-b227-36db9bda455b]  File "/Users/chelseatroy/mozilla/docker-etl/jobs/search-term-data-validation-v2/stdvv2-venv/lib/python3.11/site-packages/metaflow/cli.py", line 582, in step
[MFLOG|0|2023-12-15T15:47:19.624998Z|runtime|4025345c-c6f8-4b82-a6fc-b15e6bb77fbf]    task.run_step(
[MFLOG|0|2023-12-15T15:47:19.625014Z|runtime|5515b661-1dd8-49d2-8cd7-3f77bba842fc]  File "/Users/chelseatroy/mozilla/docker-etl/jobs/search-term-data-validation-v2/stdvv2-venv/lib/python3.11/site-packages/metaflow/task.py", line 596, in run_step
[MFLOG|0|2023-12-15T15:47:19.625033Z|runtime|683fa1b3-6f6e-4772-960c-e4a30a851d13]    self._exec_step_function(step_func)
[MFLOG|0|2023-12-15T15:47:19.625055Z|runtime|6f23d9c6-a607-4720-b21b-ec708dd93fb7]  File "/Users/chelseatroy/mozilla/docker-etl/jobs/search-term-data-validation-v2/stdvv2-venv/lib/python3.11/site-packages/metaflow/task.py", line 57, in _exec_step_function
[MFLOG|0|2023-12-15T15:47:19.625073Z|runtime|b843f0c3-da1f-4d4f-866b-e854a8692781]    step_function()
[MFLOG|0|2023-12-15T15:47:19.625088Z|runtime|bfabfea1-7a93-4941-b843-4526e982afba]  File "/Users/chelseatroy/mozilla/docker-etl/jobs/search-term-data-validation-v2/search_term_data_validation_v2/main_flow.py", line 62, in end
[MFLOG|0|2023-12-15T15:47:19.625110Z|runtime|36a77698-3fec-4dd1-837d-9ac1b2338cdf]    run = wandb.init(
[MFLOG|0|2023-12-15T15:47:19.625330Z|runtime|03006b91-3064-4e54-be94-4a33b05fc9f2]          ^^^^^^^^^^^
[MFLOG|0|2023-12-15T15:47:19.625371Z|runtime|b3b48b44-c412-4bca-a128-9eae481e025c]  File "/Users/chelseatroy/mozilla/docker-etl/jobs/search-term-data-validation-v2/stdvv2-venv/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1189, in init
[MFLOG|0|2023-12-15T15:47:19.625393Z|runtime|6aa96d95-4ade-45bd-81a7-9ccbee914b4d]    raise e
[MFLOG|0|2023-12-15T15:47:19.625412Z|runtime|bb2147b3-ae08-4eed-b448-641468ed3883]  File "/Users/chelseatroy/mozilla/docker-etl/jobs/search-term-data-validation-v2/stdvv2-venv/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1166, in init
[MFLOG|0|2023-12-15T15:47:19.625429Z|runtime|348768ce-9dc2-410b-9f95-da84c6573e09]    wi.setup(kwargs)
[MFLOG|0|2023-12-15T15:47:19.625446Z|runtime|dde88fd5-2a0b-4eff-b683-2c9151872440]  File "/Users/chelseatroy/mozilla/docker-etl/jobs/search-term-data-validation-v2/stdvv2-venv/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 306, in setup
[MFLOG|0|2023-12-15T15:47:19.625798Z|runtime|e85dc8d9-70b2-42f2-bba3-cb08967a9f77]    wandb_login._login(
[MFLOG|0|2023-12-15T15:47:19.625866Z|runtime|e0eee7b0-f476-475d-bd1e-e7c281ead552]  File "/Users/chelseatroy/mozilla/docker-etl/jobs/search-term-data-validation-v2/stdvv2-venv/lib/python3.11/site-packages/wandb/sdk/wandb_login.py", line 298, in _login
[MFLOG|0|2023-12-15T15:47:19.625898Z|runtime|75052b34-0529-47ab-bbb3-fc84dec9ed9d]    wlogin.prompt_api_key()
[MFLOG|0|2023-12-15T15:47:19.625920Z|runtime|337882af-cc87-4c43-956d-72b16ac4d6c0]  File "/Users/chelseatroy/mozilla/docker-etl/jobs/search-term-data-validation-v2/stdvv2-venv/lib/python3.11/site-packages/wandb/sdk/wandb_login.py", line 228, in prompt_api_key
[MFLOG|0|2023-12-15T15:47:19.625938Z|runtime|cb3c02f1-25fb-4e1d-9b61-4e6c99c1686e]    raise UsageError("api_key not configured (no-tty). call " + directive)
[MFLOG|0|2023-12-15T15:47:19.625959Z|runtime|3aad5fad-0cec-4195-80ff-c32fc5c10386]wandb.errors.UsageError: api_key not configured (no-tty). call wandb.login(key=[your_api_key])
[MFLOG|0|2023-12-15T15:47:19.625979Z|runtime|4da931d5-4a62-4589-a119-98d8a6ec742b]
[MFLOG|0|2023-12-15T15:47:19.626311Z|runtime|d29eabff-9d1d-490e-b8c0-e32657963c91]Task failed.